@app_url=http://127.0.0.1:5066
@app_url=https://127.0.0.1:7113
@dapr_url=http://127.0.0.1:3502

POST {{dapr_url}}/v1.0/invoke/payment/method/api/stripe/payment
Content-Type: application/json

{
  "name": "test",
  "email": "test@gmail.com",
  "orderItem": {
    "name": "sticks",
    "quantity": 10
  }
}

###
POST http://localhost:5066/api/Stripe/payment
Content-Type: application/json

{
  "name": "test",
  "email": "test@gmail.com",
  "orderItem": {
    "name": "sticks",
    "quantity": 10
  }
}