@app_port=5000
@dapr_http_port=3500 


// Product Inventory

### Get inventory
GET http://localhost:{{app_port}}/inventory

### Restock inventory
POST http://localhost:{{app_port}}/restock

### Clear inventory
DELETE http://localhost:{{app_port}}/inventory


// Checkout workflow 

### Run workflow
@workflow_id={{$guid}}

// @name wfrequest
POST http://localhost:{{dapr-http-port}}/v1.0-alpha1/workflows/dapr/CheckoutProcessingWorkflow/{{workflow_id}}/start
Content-Type: application/json

{
    "input" : {
        "Name" : "Kendall Roden",
        "Email" : "kendallroden@outlook.com",
        "OrderItem": {
        "Name": "Computers", 
        "Quantity": 20
        }
    }
}

### Get status
@workflow_id_response={{wfrequest.response.body.instance_id}}

GET http://localhost:{{dapr_http_port}}/v1.0-alpha1/workflows/dapr/CheckoutProcessingWorkflow/{{workflow_id_response}}